### ISSUE TITLE
ImportError: cannot import name 'MaskTransform' from 'Dataset.transform'

### ISSUE THREAD

**Issue by miraesposito** [NJU-LHRS/official-CMID#20]
I am attempting to run main_correspondence.py and have already set up environment.yml. I am getting the error ImportError: cannot import name 'MaskTransform' from 'Dataset.transform' when I attempt to run the code. Could you assist with this issue? The error points to line 5 in build_transform.py and transform.py.

**Comment by pUmpKin-Co** [comment]
Hi~Thanks for pointing this import error. Have been fixed!

**Comment by miraesposito** [comment]
![CMID_error](https://github.com/NJU-LHRS/official-CMID/assets/111712646/f8f2b417-0901-48a1-a4e7-99305084b035)
Thanks for the response, I pulled your most recent updates and I am still getting the error pictured here.

**Comment by pUmpKin-Co** [comment]
My fault~!:(. Have fixed, give a try.

**Comment by miraesposito** [comment]
I have a follow up question. As I mentioned, my environment is the same as yours in environment.yml, but I am getting an error regarding the MMCV version. "AssertionError: MMCV==1.6.1 is used but incompatible. Please install mmcv>=2.0.0rc4"

When I upgrade mmcv to a version greater than 2 I am met with other errors. Which version of mmcv will work for your code?

Thank you

**Comment by pUmpKin-Co** [comment]
Hi~The MMCV version of this project is 1.6.1.
I think this problem is related to other packages related to MMCV (MMsegmentation or MMRotate).Please double check the MMCV, MMsegmentation version are same as the environment file and are compatible.
